# Generated by Django 5.2.14 on 2026-06-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('spotify_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=512)),
                ('name_normalized', models.CharField(db_index=True, max_length=512)),
                ('followers_total', models.BigIntegerField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='webapp_arti_name_a705d5_idx'), models.Index(fields=['name_normalized'], name='webapp_arti_name_no_833dc0_idx'), models.Index(fields=['popularity'], name='webapp_arti_popular_591a6e_idx'), models.Index(fields=['followers_total'], name='webapp_arti_followe_c0d287_idx')],
            },
        ),
    ]
