# Generated by Django 5.2.14 on 2026-06-08 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='spotify_id',
            new_name='external_id',
        ),
    ]
